import painting1 from "../images/paintings/painting1.png";
import painting2 from "../images/paintings/painting2.png";
export const paintings = [
  {
    id: 1,
    image: painting1,
    title: "Painting 1",
    description: "This is a painting",
    year: "2020",
    price: "200",
  },
  {
    id: 2,
    image: painting1,
    title: "Painting 1",
    description: "This is a painting",
    year: "2020",
    price: "200",
  },
  {
    id: 3,
    image: painting2,
    title: "Painting 1",
    description: "This is a painting",
    year: "2020",
    price: "200",
  },
  {
    id: 4,
    image: painting2,
    title: "Painting 1",
    description: "This is a painting",
    year: "2020",
    price: "200",
  },
  {
    id: 5,
    image: painting1,
    title: "Painting 1",
    description: "This is a painting",
    year: "2020",
    price: "200",
  },
  {
    id: 6,
    image: painting2,
    title: "Painting 1",
    description: "This is a painting",
    year: "2020",
    price: "200",
  },
  {
    id: 7,
    image: painting1,
    title: "Painting 1",
    description: "This is a painting",
    year: "2020",
    price: "200",
  },
  {
    id: 8,
    image: painting2,
    title: "Painting 1",
    description: "This is a painting",
    year: "2020",
    price: "200",
  },
  {
    id: 9,
    image: painting1,
    title: "Painting 1",
    description: "This is a painting",
    year: "2020",
    price: "200",
  },

  {
    id: 10,
    image: painting2,
    title: "Painting 1",
    description: "This is a painting",
    year: "2020",
    price: "200",
  },
  {
    id: 11,
    image: painting1,
    title: "Painting 1",
    description: "This is a painting",
    year: "2020",
    price: "200",
  },
];
